services:
  app:
    image: go-tigrinho:latest
    container_name: go-tigrinho-app
    restart: unless-stopped
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: tigrinho
      PORT: "8080"
    ports:
      - "8080:8080"

